import Head from 'next/head'
import {useState} from "react";
import {ChevronLeftIcon, ChevronRightIcon, PencilIcon, PlusIcon} from '@heroicons/react/20/solid'
import {useSession} from "next-auth/react";
import Link from "next/link";
import Image from "next/image";
import {getProjects} from "../pages/api/projects"
import {useQuery} from "@tanstack/react-query";
import {BiPencil} from "react-icons/bi";
import {FaEdit, FaTrashAlt} from "react-icons/fa";


export default function Home() {
    const {data: projectsData} = useQuery('projects',getProjects);
    const [currentPage, setCurrentPage] = useState(1);
    const [projectsPerPage] = useState(6);
    const {data: session} = useSession();

    const handleClick = (event) => {
        setCurrentPage(Number(event.target.id));
    };

    const indexOfLastProject = currentPage * projectsPerPage;
    const indexOfFirstProject = indexOfLastProject - projectsPerPage;
    const currentProjects = projectsData?.slice(
        indexOfFirstProject,
        indexOfLastProject
    );
    const pageNumbers = [];
    for (let i = 0; i <= Math.ceil(projectsData?.length / projectsPerPage); i++) {
        pageNumbers.push(i);
    }
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"h-96"}>

          <a href={"/projects/[id]/edit"} className={"bg-violet-500 ml-2 border-2 p-1.5 flex rounded-2xl inline-flex text-white"}>
              <BiPencil className={"align-baseline"}/> Edit
          </a>
          <a href={"/projects/new"} className={"flex inline-flex rounded-lg p-1 border bg-indigo-400 text-white hover:bg-indigo-500"}>
              <PlusIcon className={"h-5 w-5"}/>Add project
          </a>

          <div className={"container mx-auto my-6"}>
              <h1 className={"text-3xl font-semibold mb-6"}>Projects</h1>
              <div className={"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"}>
                  {currentProjects?.map((project) => (
                      <div key={project.id} className={"bg-white rounded-lg overflow-hidden"}>
                          <div className={"relative h-64"}>
                              <Image
                                  src={project.images[0].url}
                                  alt={project.name}
                                  layout={"fill"}
                                  objectFit={"cover"}
                              />
                          </div>
                          <div className={"p-4"}>
                              <h2 className={"text-xl font-semibold mb-2"}>
                                  <Link href={`/project/${project.id}`}>{project.name}</Link>
                              </h2>
                          </div>
                      </div>
                  ))}
              </div>
          </div>

      </main>
    </>
  )
}
